name: bayesian_resnet 
base_model: resnet18 
weight_decay: 0.0005
learning_rate: 0.03
dropout_p: 0
load_pretrained: Null
# freeze_encoder: False
freeze_encoder: False
use_ema: False # True
exclude_bn_bias: True
k: 50
finetune: False # Finetuning accoring to: https://arxiv.org/abs/2101.08482
small_head: True